- name: create app root folder
  ansible.builtin.file:
    path: /app
    state: directory

- name: copy compose.yml
  ansible.builtin.template:
    src: templates/compose.yml.j2
    dest: /app/compose.yml

- name: run docker compose
  community.docker.docker_compose_v2:
    project_src: /app
    files:
      - compose.yml